apiVersion: v1
kind: Service
metadata:
  name: clinic-rest
  labels:
    app: clinic-rest
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8181
  selector:
    app: clinic-rest
